language: c
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential
  - make setup
script:
  - make compile
  - make test
notifications:
   slack: uw-cse:e7egqJduptjbd5LOn3DygfCf
